version: '3.8'

services:
  bridge1:
    build: .
    environment:
      PORT: 8081
      STORAGE_TYPE: memory
      CORS_ENABLE: "true"
      HEARTBEAT_INTERVAL: 10
      RPS_LIMIT: 1000
      CONNECTIONS_LIMIT: 200
    networks:
      - bridge_network
    restart: unless-stopped

  bridge2:
    build: .
    environment:
      PORT: 8081
      STORAGE_TYPE: memory
      CORS_ENABLE: "true"
      HEARTBEAT_INTERVAL: 10
      RPS_LIMIT: 1000
      CONNECTIONS_LIMIT: 200
    networks:
      - bridge_network
    restart: unless-stopped

  bridge3:
    build: .
    environment:
      PORT: 8081
      STORAGE_TYPE: memory
      CORS_ENABLE: "true"
      HEARTBEAT_INTERVAL: 10
      RPS_LIMIT: 1000
      CONNECTIONS_LIMIT: 200
    networks:
      - bridge_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bridge1
      - bridge2
      - bridge3
    networks:
      - bridge_network
    restart: unless-stopped

networks:
  bridge_network:
    driver: bridge
